# variable for md files
mds = $(wildcard paper/sections/*.md)


# phony target
.PHONY: all clean


# all
all: paper.html paper.md


# sections to paper.html
paper.html: $(mds)
	pandoc $(mds) -s -o paper/paper.html


# sections to paper.md
paper.md: $(mds)
	pandoc $(mds) -s -o paper/paper.md
